spring:
  application:
    name: 'hello-spring-boot'
  datasource:
    url: 'jdbc:mysql://localhost:3306/db_spring_boot_devteria'
    username: root
    password: aA@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
  servlet:
    context-path: /identity

jwt:
  secret: "wz6FV0R+LKoRD9Y1FeMTN/ODMD/dWA+wWY71ylARo0raPZ4j"
#  expiration: 86400000 #1d
  expiration: 60000 #1p




